export const services = [
  {
    slug: "interior-design",
    title: "Interior Design",
    blurb: "Bespoke spatial design that transforms how you live, work, and feel.",
    detail: "Our interior design studio crafts spaces with intention — balancing form, function, and atmosphere. From open-concept living areas to intimate reading nooks, every element is placed with purpose. We work with natural light, material textures, and curated color palettes to create environments that feel effortlessly sophisticated.",
    icon: "✦",
  },
  {
    slug: "smart-home",
    title: "Smart Home Systems",
    blurb: "Intelligent automation that anticipates your every need.",
    detail: "We integrate cutting-edge home automation — from Crestron and Lutron lighting control to whole-house audio by Sonos and Bang & Olufsen. Motorized shades, climate zones, security systems, and voice-activated everything — all controlled from a single, elegant interface on your wall or phone.",
    icon: "◈",
  },
  {
    slug: "luxury-furniture",
    title: "Luxury Furniture",
    blurb: "Curated collections from Italy, Scandinavia, and Japanese craftsmen.",
    detail: "We source and commission furniture from the world's finest makers — B&B Italia, Minotti, Fritz Hansen, and bespoke Japanese woodworkers. Every sofa, dining table, and accent chair is selected not just for beauty, but for how it shapes the rhythm of daily life in your home.",
    icon: "◇",
  },
  {
    slug: "lighting-design",
    title: "Lighting Design",
    blurb: "Architectural lighting that sculpts mood and reveals texture.",
    detail: "Light is the invisible furniture of a room. Our lighting designers create layered schemes — ambient, task, accent, and decorative — using fixtures from Flos, Artemide, and custom fabricators. We design for circadian rhythm support, artwork illumination, and dramatic evening atmospheres.",
    icon: "○",
  },
  {
    slug: "home-theater",
    title: "Home Theater & Audio",
    blurb: "Cinema-grade entertainment systems engineered for your space.",
    detail: "From dedicated home theaters with 4K laser projectors and Dolby Atmos to distributed multi-room audio, we design entertainment experiences that rival commercial venues. Acoustic treatment, calibrated displays, and invisible speaker integration make every viewing unforgettable.",
    icon: "△",
  },
  {
    slug: "kitchen-design",
    title: "Kitchen Design",
    blurb: "Professional-grade kitchens with artisan materials and smart appliances.",
    detail: "The kitchen is the heart of modern living. We design with Gaggenau, Miele, and Sub-Zero appliances, natural stone countertops, and custom cabinetry. Integrated technology — smart ovens, connected refrigerators, and automated ventilation — makes cooking effortless and entertaining seamless.",
    icon: "□",
  },
  {
    slug: "bathroom-spa",
    title: "Bathroom & Spa",
    blurb: "Wellness sanctuaries with heated surfaces and rain systems.",
    detail: "Transform your bathroom into a personal spa. Freestanding tubs from Victoria + Albert, rainfall shower systems by Dornbracht, heated stone floors, chromotherapy lighting, and smart mirrors with integrated displays — every detail designed for daily ritual and rejuvenation.",
    icon: "◎",
  },
  {
    slug: "outdoor-living",
    title: "Outdoor Living",
    blurb: "Seamless indoor-outdoor transitions with designer terraces.",
    detail: "We extend your living space beyond walls with motorized glass wall systems, outdoor kitchens, fire features, and weather-resistant furniture by Dedon and Kettal. Landscape lighting, irrigation automation, and climate-controlled pergolas create year-round outdoor luxury.",
    icon: "⬡",
  },
  {
    slug: "art-curation",
    title: "Art & Object Curation",
    blurb: "Gallery-quality art advisory and collection display design.",
    detail: "Our art advisors source original works, limited editions, and sculptural objects that resonate with your space and sensibility. We design museum-grade display systems with proper lighting, climate control, and anti-theft measures for collections that appreciate in value and meaning.",
    icon: "◆",
  },
];
